### ISSUE TITLE
Text view not updating correctly

### ISSUE THREAD

**Issue by slav-petev** [vv-b-s/AsciiToText#1]
> Description: When we modify the numeric representation of a letter, the text view does not update correctly
Steps to reproduce:

- Start ASCII to Text
- Enter the text "Slav will help Valio" in the text view
- Select "Binary" from the dropdown menu.
- In the numeric view, place the cursor between the first and second numeric representation, 
  with the cursor closer to the first.
- Delete the last digit from the first numeric representation.

Expected Result:
- ")lav will help Valio"

Actual Result:
![actual value](https://cloud.githubusercontent.com/assets/19415061/22758597/054a1e90-ee58-11e6-8154-4d03f5130441.png)

**Comment by vv-b-s** [comment]
Issue Addressed and fixed. =)
